version: '3.8'
services:
  dev-db:
    image: postgres
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12343
      POSTGRES_DB: nest
    networks:
      - bookmarks
networks:
 bookmarks: